# Generated by Django 5.2.6 on 2025-10-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="movie",
            table="movies_movie",
        ),
    ]
