# Generated by Django 5.2.6 on 2025-10-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_poster"),
        ("movies", "0003_alter_movie_table"),
    ]

    operations = []
