# Generated by Django 5.2.6 on 2025-10-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_merge_0002_movie_poster_0003_alter_movie_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
    ]
